// packages/svelte/ui/custom-button.svelte
<script>
    export let title;
    export let text;
    export let onCLick;

</script>


<button on:click={onCLick} title={title}>

{text}


</button>

<style>
    button {
        border: none;
        padding: 0.5rem 2rem;
        color: #fff;
        font-size: 1.5rem;
        border-radius: 1rem;
        box-shadow: 0px 3px 3px rgba(0, 0, 0, 0.25);
        background-color: rgb(105, 151, 250);
    }
</style>

// packages/react/ui/custom-button.tsx
import React from "react";

export const CustomButton = (
  title: string = "",
  text: string = "",
  onClick = () => {}
) => {
  const style = {
    border: "none",
    padding: " 0.5rem 2rem",
    color: "#fff",
    fontSize: "1.5rem",
    borderRadius: "1rem",
    backgroundColor: "rgb(105, 151, 250)",
  };

  return (
    <button title={title} onClick={onClick} {...style}>
      {text}
    </button>
  );
};
