// packages/svelte/CustomButton.svelte
<script>
    export let title;
    export let text;
    export let onClick;

</script>

<button on:click={onClick} title={title}>
    {text}
</button>

<style>
    button {
        border: none;
        padding: 0.5rem 2rem;
        color: #fff;
        font-size: 1.5rem;
        border-radius: 1rem;
        transition: all 250ms;
        transform-origin: center;
        box-shadow: 0px 3px 3px rgba(0, 0, 0, 0.25),
        inset 0px -2px 3px rgba(0, 0, 0, 0.25);
        background-color: green;
    }
    button:hover {
        cursor: pointer;
        transform: scale(0.975);
        box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.25);
    }
</style>

// packages/react/custom-button.tsx
export const CustomButton = (
  title: string = "",
  text: string = "",
  onClick: () => void
) => {
  const style = {
    border: "none",
    padding: " 0.5rem 2rem",
    color: "#fff",
    fontSize: "1.5rem",
    borderRadius: "1rem",
    backgroundColor: "rgb(105, 151, 250)",
  };

  return (
    <button title={title} onClick={onClick} {...style}>
      {text}
    </button>
  );
};
